### ISSUE TITLE
@Data

### ISSUE THREAD

**Issue by difiozy** [Umnica/quizapp#2]
https://github.com/Umnica/quizapp/blob/56c9d5321b79c370f2f5b388e647a4a2513a7c21/src/main/java/com/vtortsev/quizapp/controller/QuestionController.java#L12

@Data пишется над POJO объектами, писать ее над контроллерами неуместно, контроллер не является дата классом и не переносит никакой информации

**Comment by Umnica** [comment]
понял, исправил
