### ISSUE TITLE
Json

### ISSUE THREAD

**Issue by difiozy** [Umnica/quizapp#23]
https://github.com/Umnica/quizapp/blob/90e092620c3be62fceb8b797c4a5a40b58acf12c/src/main/java/com/vtortsev/quizapp/entities/Answer.java#L9C1-L9C1

здесь не нужно игнорировать эти проперти, если они возвращаются из контроллера, то нужно их просто перемапить в другой объект

**Comment by Umnica** [comment]
https://github.com/Umnica/quizapp/blob/json/src/main/java/com/vtortsev/quizapp/controller/AnswerController.java
грусть печаль, не понимаю, что я сделал не так
