### ISSUE TITLE
Requests paths naming

### ISSUE THREAD

**Issue by difiozy** [Umnica/quizapp#4]
https://github.com/Umnica/quizapp/blob/56c9d5321b79c370f2f5b388e647a4a2513a7c21/src/main/java/com/vtortsev/quizapp/controller/QuestionController.java#L23

Наименование allQuestions не подходит по стандартные наименования ресурсов в rest, подумай над более подходящим именем и форматом записи пути (camelCase не используют в rest путях)

**Comment by Umnica** [comment]
понял, сделал @GetMapping("/all")
